tallerconfiable53/Models/ErrorViewModel.cs
namespace tallerconfiable53.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

tallerconfiable53/Models/mecanicoModelo.cs
using System.ComponentModel.DataAnnotations;
namespace tallerconfiable53.Models
{
    public class mecanicoModelo
    {
        public int idPersona { get; set; }
        public string? identificacion { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? nombre { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? apellido { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? anoNacimiento { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? telefono { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? direccion { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? nivelEducativo { get; set; }

    }
}

tallerconfiable53/Models/personaModelo.cs
using System.ComponentModel.DataAnnotations;

namespace tallerconfiable53.Models

{
    public class personaModelo
    {
        public int idPersona { get; set;}
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? identificacion { get; set;}
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? nombre { get; set;}
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? apellido { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? anoNacimiento { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? ciudad { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? email { get; set; }
    }
}

tallerconfiable53/Models/vehiculoModelo.cs
using System.ComponentModel.DataAnnotations;

namespace tallerconfiable53.Models
{
    public class vehiculoModelo
    {
        public int idVehiculo { get; set; }
        public int idPropietario { get; set; }
        public int  identificacion{ get; set; }
        public string? placa { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? tipo { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? marca { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? modelo { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? capacidad { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        public string? cilindraje { get; set; }
        public string? ciudadOrigen { get; set; }
        public string? descripcion { get; set; }
    }
}

tallerconfiable53/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tallerconfiable53.Models;

namespace tallerconfiable53.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tallerconfiable53/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using tallerconfiable53.Datos;
using tallerconfiable53.Models;

namespace tallerconfiable53.Controllers
{
    public class MantenedorController : Controller
    {
        personaDatos _PersonaDatos = new personaDatos();
        public IActionResult Listar()
        {
            //listar contactos
            var oLista = _PersonaDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //devuelve la vista

            return View();
        }

        [HttpPost]
        public IActionResult Guardar(personaModelo oPersona)
        {
            //validacion de campos
            if (!ModelState.IsValid)
                return View();
            //recibe un objeto y guarda en la base de datos
            var respuesta = _PersonaDatos.Guardar(oPersona);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int idPersona)
        {
            //devuelve la vista
            var opersona = _PersonaDatos.Obtener(idPersona);
            return View(opersona);
        }

        [HttpPost]
        public IActionResult Editar(personaModelo oPersona)
        {
            //validacion de campos
            if (!ModelState.IsValid)
                return View();
            //recibe un objeto y guarda en la base de datos
            var respuesta = _PersonaDatos.Editar(oPersona);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int idPersona)
        {
            //devuelve la vista
            var opersona = _PersonaDatos.Eliminar(idPersona);
            return View();
        }

        [HttpPost]
        public IActionResult Eliminar(personaModelo oPersona)
        {
            //recibe un objeto y guarda en la base de datos
            var respuesta = _PersonaDatos.Eliminar(oPersona.idPersona);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

tallerconfiable53/Controllers/MecanicoController.cs
using Microsoft.AspNetCore.Mvc;
using tallerconfiable53.Datos;
using tallerconfiable53.Models;

namespace tallerconfiable53.Controllers
{
    public class MecanicoController : Controller
    {
        mecanicoDatos _MecanicoDatos = new mecanicoDatos();
        public IActionResult Listar()
        {
            //listar contactos
            var oLista = _MecanicoDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            //devuelve la vista

            return View();
        }

        [HttpPost]
        public IActionResult Guardar(mecanicoModelo oMecanico)
        {
            //validacion de campos
            if (!ModelState.IsValid)
                return View();
            //recibe un objeto y guarda en la base de datos
            var respuesta = _MecanicoDatos.Guardar(oMecanico);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int idPersona)
        {
            //devuelve la vista
            var opersona = _MecanicoDatos.Obtener(idPersona);
            return View(opersona);
        }

        [HttpPost]
        public IActionResult Editar(mecanicoModelo oMecanico)
        {
            //validacion de campos
            if (!ModelState.IsValid)
                return View();
            //recibe un objeto y guarda en la base de datos
            var respuesta = _MecanicoDatos.Editar(oMecanico);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int idPersona)
        {
            //devuelve la vista
            var opersona = _MecanicoDatos.Eliminar(idPersona);
            return View();
        }

        [HttpPost]
        public IActionResult Eliminar(personaModelo oMecanico)
        {
            //recibe un objeto y guarda en la base de datos
            var respuesta = _MecanicoDatos.Eliminar(oMecanico.idPersona);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }
    
        public IActionResult Index()
        {
            return View();
        }
    }
}

tallerconfiable53/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Bienvenido a el taller confiable</h1>
    <h2>Hola mundo</h2>
        <p>
            En esta aplicacion encontraras nuestro proyecto
            al que le hemos dedicado mucho esfuerzo y trabajo duro.
            Muchas gracias por visitarnos. :)
        </p>
    <asp:Image ID="imgImagen" runat="server" ImageUrl="~/Img/KYOcode.png" AlternateText="kyocode" />
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

tallerconfiable53/Views/Mantenedor/Editar.cshtml
@model personaModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<div class="card">
    <div class="card-header">
        Editar persona
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for=" idPersona" type="hidden" class="form-control" />
            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="identificacion" type="text" class="form-control" />
                <span asp-validation-for="identificacion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombre" type="text" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellido" type="text" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Año de nacimiento</label>
                <input asp-for="anoNacimiento" type="text" class="form-control" />
                <span asp-validation-for="anoNacimiento" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Ciudad</label>
                <input asp-for="ciudad" type="text" class="form-control" />
                <span asp-validation-for="ciudad" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Email</label>
                <input asp-for="email" type="text" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Editar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

tallerconfiable53/Views/Mantenedor/Eliminar.cshtml
@model personaModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<div class="card">
    <div class="card-header">
        Eliminar Persona
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">

            <input asp-for="idPersona" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el contacto : @Html.DisplayTextFor(m => m.nombre) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Voler a la lista</a>
        </form>

    </div>
</div>

tallerconfiable53/Views/Mantenedor/Guardar.cshtml
@model personaModelo
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Guardar</h1>

<div class="card">
    <div class="card-header">
        Crear persona
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="identificacion" type="text" class="form-control" />
                <span asp-validation-for="identificacion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombre" type="text" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellido" type="text" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Año de nacimiento</label>
                <input asp-for="anoNacimiento" type="text" class="form-control" />
                <span asp-validation-for="anoNacimiento" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Ciudad</label>
                <input asp-for="ciudad" type="text" class="form-control" />
                <span asp-validation-for="ciudad" class="text-danger"></span>
            </div>
            
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input asp-for="email" type="text" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

tallerconfiable53/Views/Mantenedor/Listar.cshtml
@model List<personaModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listar</h1>

<div class="card">

    <div class="card-header">
        Listar Persona / Propietario
    </div>

    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success"><i class="bi bi-plus-circle"></i> Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Identificacion</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha de nacimiento</th>
                    <th>Ciudad</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.identificacion</td>
                        <td>@item.nombre</td>
                        <td>@item.apellido</td>
                        <td>@item.anoNacimiento</td>
                        <td>@item.ciudad</td>
                        <td>@item.email</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-idPersona="@item.idPersona">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-idPersona="@item.idPersona">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

tallerconfiable53/Views/Mecanico/Editar.cshtml
@model mecanicoModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<div class="card">
    <div class="card-header">
        Editar Mecanico
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Mecanico" method="post">
            <input asp-for=" idPersona" type="hidden" class="form-control" />
            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="identificacion" type="text" class="form-control" />
                <span asp-validation-for="identificacion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombre" type="text" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellido" type="text" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Año de nacimiento</label>
                <input asp-for="anoNacimiento" type="text" class="form-control" />
                <span asp-validation-for="anoNacimiento" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Telfono</label>
                <input asp-for="telefono" type="text" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="direccion" type="text" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Nivel de Educacion</label>
                <input asp-for="nivelEducativo" type="text" class="form-control" />
                <span asp-validation-for="nivelEducativo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Editar</button>
            <a asp-action="Listar" asp-controller="Mecanico" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

tallerconfiable53/Views/Mecanico/Eliminar.cshtml
@model mecanicoModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<div class="card">
    <div class="card-header">
        Eliminar Mecanico
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Mecanico" method="post">

            <input asp-for="idPersona" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el contacto : @Html.DisplayTextFor(m => m.nombre) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mecanico" class="btn btn-warning">Voler a la lista</a>
        </form>

    </div>
</div>

tallerconfiable53/Views/Mecanico/Guardar.cshtml
@model mecanicoModelo
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Guardar</h1>

<div class="card">
    <div class="card-header">
        Crear Mecanico
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Mecanico" method="post">
            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="identificacion" type="text" class="form-control" />
                <span asp-validation-for="identificacion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombre" type="text" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellido" type="text" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Año de nacimiento</label>
                <input asp-for="anoNacimiento" type="text" class="form-control" />
                <span asp-validation-for="anoNacimiento" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Telfono</label>
                <input asp-for="telefono" type="text" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="direccion" type="text" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Nivel de Educacion</label>
                <input asp-for="nivelEducativo" type="text" class="form-control" />
                <span asp-validation-for="nivelEducativo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mecanico" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

tallerconfiable53/Views/Mecanico/Listar.cshtml
@model List<mecanicoModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listar</h1>

<div class="card">

    <div class="card-header">
        Listar Mecanico
    </div>

    <div class="card-body">

        <a asp-action="Guardar" asp-controller="Mecanico" class="btn btn-success"><i class="bi bi-plus-circle"></i> Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Identificacion</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha de nacimiento</th>
                    <th>Telefono</th>
                    <th>Direccion</th>
                    <th>Nivel de Educacion</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                        <tr>
                            <td>@item.identificacion</td>
                            <td>@item.nombre</td>
                            <td>@item.apellido</td>
                            <td>@item.anoNacimiento</td>
                            <td>@item.telefono</td>
                            <td>@item.direccion</td>
                            <td>@item.nivelEducativo</td>
                            <td>
                                <a asp-action="Editar" asp-controller="Mecanico" class="btn btn-primary btn-sm" asp-route-idPersona="@item.idPersona">Editar</a>
                                <a asp-action="Eliminar" asp-controller="Mecanico" class="btn btn-danger btn-sm" asp-route-idPersona="@item.idPersona">Eliminar</a>
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </div>

</div>

tallerconfiable53/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tallerconfiableG53</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tallerconfiable53.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tallerconfiable53</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Welcome Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Politicas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mantenedor" asp-action="Listar">Propietario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mecanico" asp-action="Listar">Mecanico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="vehiculo" asp-action="Listar">Vehiculo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - tallerconfiable53 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

tallerconfiable53/Views/vehiculo/Editar.cshtml
@model vehiculoModelo
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<div class="card">
    <div class="card-header">
        Editar Vehiculo
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="vehiculo" method="post">
            <input asp-for=" idPropietario" type="hidden" class="form-control" />

            <div class="mb-3">
                <label class="form-label">Identificacion</label>
                <input asp-for="identificacion" type="text" class="form-control" />
                <span asp-validation-for="identificacion" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Placa</label>
                <input asp-for="placa" type="text" class="form-control" />
                <span asp-validation-for="placa" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Tipo</label>
                <input asp-for="tipo" type="text" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Marca</label>
                <input asp-for="marca" type="text" class="form-control" />
                <span asp-validation-for="marca" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Modelo</label>
                <input asp-for="modelo" type="text" class="form-control" />
                <span asp-validation-for="modelo" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Capacidad</label>
                <input asp-for="capacidad" type="text" class="form-control" />
                <span asp-validation-for="capacidad" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Clilindraje</label>
                <input asp-for="cilindraje" type="text" class="form-control" />
                <span asp-validation-for="cilindraje" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Ciudad de Origen</label>
                <input asp-for="ciudadOrigen" type="text" class="form-control" />
                <span asp-validation-for="ciudadOrigen" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Descripcion</label>
                <input asp-for="descripcion" type="text" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Editar</button>
            <a asp-action="Listar" asp-controller="vehiculo" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

tallerconfiable53/Views/vehiculo/Eliminar.cshtml
@model vehiculoModelo
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<div class="card">
    <div class="card-header">
        Eliminar Vehiculo
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="vehiculo" method="post">

            <input asp-for="idPropietario" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el contacto : @Html.DisplayTextFor(m => m.placa) ?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="vehiculo" class="btn btn-warning">Voler a la lista</a>
        </form>
    </div>
</div>